### ISSUE TITLE
Geoid no longer required

### ISSUE THREAD

**Issue by ifly7charlie** [kerel-fs/ogn-node#3]
Latest versions determine it by packet if it is not configured. By configuring it in the configuration file there is a high likelihood that incorrect elevations will be reported for packets, and gliders will appear to "jump" up and down as different receivers process the packets.

Please remove geoid configuration!

**Comment by kerel-fs** [comment]
Thank you for caring about this project.
The last change in this repository is 4 years old though and thus it is obviously unmaintained. I'll reconsider to mark it as "archived" to avoid getting further requests of this kind.

If you are interested in this repository and want to develop on & use it, consider to base your work on the fork [lordfolken/ogn-node](https://github.com/lordfolken/ogn-node) by @lordfolken which got several improvements.

Best wishes, kerel

**Comment by ifly7charlie** [comment]
Thanks,
I’ve updated document that linked to project to say not supported as well
Mel

**Comment by lordfolken** [comment]
@ifly7charlie @kerel-fs i have added a commit here:
https://github.com/lordfolken/ogn-node/commit/0c99eb1497cc1bac4e8285b3bf640862e0bdd549 
i should have upstreamed to kerel-fs's work.
